server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: shipping-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/shipping_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # 数据库初始化配置
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true




mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shipping.model

# JWT配置
jwt:
  secret: shipping-system-jwt-secret-key-2023
  expiration: 86400000  # 24小时，单位毫秒

# 高德地图API配置
amap:
  key: your-amap-api-key
  web-api-url: https://restapi.amap.com/v3

# Swagger文档配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

# 日志配置
logging:
  level:
    com.shipping: DEBUG
    org.springframework.security: DEBUG
    com.shipping.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/shipping-system.log 